title: "Визуальная новелла"
markdown: kramdown
baseurl: "/WebNovyll"
url: "https://njko39.github.io"

plugins:
  - jekyll-collections
  - jekyll-redirect-from

collections:
  story:
    output: true
    permalink: "/story/:name/"

defaults:
  - scope:
      path: ""
      type: "story"
    values:
      layout: "story"
