title: "Визуальная новелла"
markdown: kramdown
baseurl: "/WebNovyll"  # Если сайт размещён в корне домена, оставь пустым. 
url: "https://njko39.github.io"  # Поменяй на свой домен при деплое

collections:
  story:
    output: true
    permalink: "/WebNovyll/story/:name/"
