title: "Визуальная новелла"
markdown: kramdown
baseurl: ""  # Если сайт размещён в корне домена, оставь пустым. 
url: "http://localhost:4000"  # Поменяй на свой домен при деплое

collections:
  story:
    output: true
    permalink: "/story/:name/"
